= JCStress
Es una herramienta la cual nos permite hacer tests de concurrencia.

== Quick start
Necesitaremos instalar Mercurial, Maven y Java 8.

* Check out source code
	- hg clone http://hg.openjdk.java.net/code-tools/jcstress/ jcstress (La herramienta ya esta usando Java 9 por lo cual podemos hacer un clone hasta una revision anterior para usar Java 8 hg clone http://hg.openjdk.java.net/code-tools/jcstress/ -r 261 jcstress)
	- cd jcstress/
* Build jcstress
	- mvn clean install -pl tests-custom -am (Dado que es un proyecto grande, solo ejecutamos el build para un subset minimo de proyectos)
	- Podemos usar "java -jar tests-custom/target/jcstress.jar -h" para obtener ayuda sobre los parametros

== Nuestro primer test

Para crear nuestro primer test, podemos agregarlos en la carpeta "tests-custom" del mismo repositorio de jcstress, o podemos crear un nuevo proyecto que tenga de dependencia a jcstress. Para nuestros ejemplos vamos a crear un nuevo proyecto que tenga la dependencia de jcstress y lo ejecutaremos por medio de un plugin gradle

https://github.com/jerzykrlk/jcstress-gradle-plugin[JCStress Gradle Plugin]

Nuestro test estaran contenidos en el proyecto "JCStressTestCases", si vemos el test "BitSetConcurrencyTest" encontraremos algunos comentarios sobre las annotations basicas de jcstress.
