= JCStress
Es una herramienta la cual nos permite hacer tests de concurrencia.

== Quick start
Necesitaremos instalar Mercurial, Maven y Java 8.

* Check out source code
	- hg clone http://hg.openjdk.java.net/code-tools/jcstress/ jcstress (La herramienta ya esta usando Java 9 por lo cual podemos hacer un clone hasta una revision anterior para usar Java 8 hg clone http://hg.openjdk.java.net/code-tools/jcstress/ -r 261 jcstress)
	- cd jcstress/
* Build jcstress
	- mvn clean install -pl tests-custom -am (Dado que es un proyecto grande, solo ejecutamos el build para un subset minimo de proyectos)
	- Podemos usar "java -jar tests-custom/target/jcstress.jar -h" para obtener ayuda sobre los parametros

== Nuestro primer test

Para crear nuestro primer test, podemos agregarlos en la carpeta "tests-custom" del mismo repositorio de jcstress, o podemos crear un nuevo proyecto que tenga de dependencia a jcstress. Para nuestros ejemplos vamos a crear nuevos proyectos
que tenga la dependencia de jcstress y lo ejecutaremos por medio de un plugin gradle para ejecutar jcstress

https://github.com/jerzykrlk/jcstress-gradle-plugin[JCStress Gradle Plugin]

Para tener una idea de un test simple podemos ver el proyecto "JCStressTutorial", el cual contiene una clase llamada "BitSetConcurrencyTest" con la explicacion de las annotations que utilizamos con jcstress, luego podemos ver los resultados en un HTML generado en la carpeta "results"
Si ejecutamos los test del proyecto de "JCStressTutorial" veremos que los tres casos mencionados con las annotations @Outcome pueden suceder, lo cual podria no ser lo esperado ya que cada Thread esta escribiendo un valor distinto, la explicacion de porque sucede este comportamiento la veremos en las slides traducidas cuando se hable de Word Tearing, si leemos la documentacion de BitSet veremos que dice que no es Thread Safe por lo cual para arreglar el test podemos incluir un bloque synchronized para cada actor.

[source,java]
----
@Actor
public void thread1() {
	synchronized (sharedBitSet) {
		sharedBitSet.set(1);
	}
}

@Actor
public void thread2() {
	synchronized (sharedBitSet) {
		sharedBitSet.set(2);
	}
}
----

